### ISSUE TITLE
Add a release

### ISSUE THREAD

**Issue by FFY00** [getpatchwork/pwclient#2]
Hello, would it be possible to add a release so that pwclient can be properly packaged by distributions?

Thanks,
Filipe

**Comment by stephenfin** [comment]
Sure thing. I'm working on adding a load of unit tests to this and splitting the single file up into modules. I almost finished it this weekend and should have it totally finished by next week.

**Comment by FFY00** [comment]
Great :smile:.

**Comment by stephenfin** [comment]
pwclient 1.0.0 has been [released](https://pypi.org/project/pwclient/).

**Comment by FFY00** [comment]
Thanks!
