### ISSUE TITLE
Are the entries in .pwclientrc servers or projects?

### ISSUE THREAD

**Issue by rossburton** [getpatchwork/pwclient#24]
There appears to be some confusion as to whether the entries in `.pwclientrc` are _servers_ or _projects_.

Should it list _projects_, so I should have a "glibc" entry for https://patchwork.sourceware.org/project/glibc/ if I then wanted to search the gcc project too, I should copy-paste the block entirely as the URL and auth token are identical?

Or should the pwclientrc file list _servers_ as settings like custom states are per-server, and ensure that any confusion in the code between the server and the project is cleared up?

Discovered as I had a patchwork entry for "yocto" and the lookup-by-hash functionality wasn't working as whilst it was hitting the right server, it was telling the server to restrict my search to the "yocto" project, but that doesn't exist.

**Comment by stephenfin** [comment]
Unfortuantely it's the latter, projects. We could add a `project`/`defaultproject` key and allow the section titles to be anything, but currently that's the way it's structured.

**Comment by stephenfin** [comment]
To follow up on your other question, yes, you'd currently need to duplicate the section contents and use a different section title for each project you want to support on a given server.
